name: Test
on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Build image
      run: make build
